version: '3.4'

services:
   db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: 'a1234567890b'
      POSTGRES_DB: "gobarberts"
    ports:
      - "5432:5432"

   mongo:
    image: 'mongo'
    restart: always
    ports:
      - '27017:27017'

